### ISSUE TITLE
TypeError: Cannot read property 'Fr' of undefined

### ISSUE THREAD

**Issue by ChihChengLiang** [weijiekoh/libsemaphore#3]
## What's wrong

A fresh installation of libsemaphore will throw this error.

```
$ node
Welcome to Node.js v12.14.1.
Type ".help" for more information.
> libsemaphore = require('libsemaphore')
Thrown:
TypeError: Cannot read property 'Fr' of undefined
    at Object.<anonymous> (/Users/liangcc/projects/EAPL/semaphore_projects/semaphore_auth/packages/frontend/node_modules/circomlib/src/poseidon.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```

The cause of the exception is `circomlib@0.0.21` requires bn128 from `snarkjs^0.1.20`, which no longer provides bn128 since 0.1.25 (released 5 days ago).

```js
// circomlib@0.0.21 circomlib/src/poseidon.js
const bn128 = require("snarkjs").bn128; // bn128 not available after 0.1.25
...
const F = bn128.Fr;
```

## How can it be fixed

Bump circomlib to 0.1.x, which does not require bn128 at the same line.

**Comment by ChihChengLiang** [comment]
`mkdir test && cd test && npm init && npm install libsemaphore`

Running the above script in this setting does not throw an error.

Further investigation shows using yarn for my project might be the cause of the error. yarn doesn't respect the package-lock in circomlib, which locks the correct snarkjs version. 
After removing yarn and reinstalling the deps with npm it works.
